### PR TITLE
Generator/vite react app

### PR DESCRIPTION
**Pull request by Mysh3ll**
Integration of Vite React app with:

- Typescript
- ESLint (@thetribe/eslint-config-react-typescript)
- Vitest
- Testing Library
- React Router

Based on `create-react-app` generator

### CODE REVIEW

**Review by jvasseur — CHANGES_REQUESTED** [review]
A big :-1: for me to merge this PR because this adds an additional generator to maintain without adding another sack.

For me the goal of this project is to chose the best possible tools and config for each stack and propose a generator for them so either we still think CRA is the best tooling available for a React app (I personally think this is the case, not necessarily because of the solution's merits but because everyone is more used to it), or we decide that Vite is better and then we replace the CRA generator with a Vite one.

**Comment by jvasseur** [comment]
And if we still decide to go with adding this option, this should be an option in a common (with CRA) React generator to reduce code duplication.

**Comment by Mysh3ll** [comment]
I completely understand your point of view. Indeed, we can always debate the relevance between CRA and Vite.

**Comment by jvasseur** [comment]
We will probably switch to an esbuild based solution at some point for better perfs but this is something that need to be tested and validated as a best practice before contributing it to the generator.

**Comment by Mysh3ll** [comment]
ok, in this case I suggest you close the PR

**Pull request closed without merging**
